name: Trigger auto deployment for azps-containerapp-1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/azps-containerapp-1-AutoDeployTrigger-7ef046d8-3bac-47d7-b370-91ea90127f78.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZPSCONTAINERAPP1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZPSCONTAINERAPP1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZPSCONTAINERAPP1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: azpscontainerregistry.azurecr.io
          registryUsername: ${{ secrets.AZPSCONTAINERAPP1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZPSCONTAINERAPP1_REGISTRY_PASSWORD }}
          containerAppName: azps-containerapp-1
          resourceGroup: my-arc-cluster-group
          imageToBuild: azpscontainerregistry.azurecr.io/azps-containerapp-1:${{ github.sha }}
          dockerfilePath: Dockerfile


