name: Trigger auto deployment for azps-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/azps-containerapp-AutoDeployTrigger-e462e403-8c9c-41c2-aa20-b2f69330682d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: azpsacr.azurecr.io
          username: ${{ secrets.AZPSCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.AZPSCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azpsacr.azurecr.io/testimage/tag:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZPSCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n azps-containerapp -g azpstest_gp --server azpsacr.azurecr.io --username  ${{ secrets.AZPSCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.AZPSCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n azps-containerapp -g azpstest_gp --image azpsacr.azurecr.io/testimage/tag:${{ github.sha }}
